@VehicleProject_HostAddress = http://localhost:5230

GET {{VehicleProject_HostAddress}}/Car
Accept: application/json

###
POST {{VehicleProject_HostAddress}}/Car
Content-Type: application/json

{
    "Make": "Red",
    "Model": "Honda",
    "Engine": "V4",
    "Doors": 4,
    "Wheels": 4,
    "VehicleType": "Car",
    "BodyType": "Sedan"
}
{
    "Model": "Grand i10",
    "Bodytype": "Sedan",
    "Doors": "4",
    "Engine": "V4",
    "Wheels": "4",
    "Make": "Gray"
}
###
GET {{VehicleProject_HostAddress}}/Car/2
Accept: application/json

###
DELETE {{VehicleProject_HostAddress}}/Car/3

###
GET {{VehicleProject_HostAddress}}/Car/fields
Accept: application/json